export const Routes = {
  HOME: "home",
  ALL_CATEGORIES: "all_categories",
  PRODUCTS: "products",
  HOME_STACK: "home_stack",
  CART_STACK: "cart_stack",
  PROFILE_STACK: "profile_stack",
  NOTIFICATION: "notification",
  CART: "cart",
  CHECKOUT: "checkout",
  ORDERS: "orders",
  PROFILE: "profile",
  PRODUCT_DETAIL: "product_detail",
  FAVORITES: "favorites",
  ADDRESS: "address",
  ADD_ADDRESS: "add_address",
};
